<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Struktur Organisasi - Pragya Dharma</title>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    <link rel="stylesheet" href="{{ asset('css/style.css') }}">
 
</head>
<body class="bg-gray-50">
    <!-- Main Content -->
    <main class="container mx-auto px-4 py-8 max-w-7xl">
        <div class="text-sm text-red-700 font-medium mb-6">
            Struktur Organisasi
        </div>

        <!-- Title -->
        <h1 class="text-4xl md:text-5xl font-bold text-gray-900 mb-8">
            Nama Divisi
        </h1>

        <!-- Hero Image -->
        <div class="w-full rounded-3xl overflow-hidden mb-8 shadow-lg">
            <img 
                src="https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=1200&h=400&fit=crop" 
                alt="Students studying together" 
                class="w-full h-64 md:h-96 object-cover"
            >
        </div>

        <!-- Description Text -->
        <div class="text-gray-600 leading-relaxed text-justify mb-16 space-y-4">
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce in vehicula ex. Pellentesque sollicitudin ex et dictum faucibus Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce in vehicula ex. Pellentesque sollicitudin ex et dictum faucibus...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce in vehicula ex. Pellentesque sollicitudin ex et dictum faucibus...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce in vehicula ex. Pellentesque sollicitudin ex et dictum faucibus...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce in vehicula ex. Pellentesque sollicitudin ex et dictum faucibus...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce in vehicula ex. Pellentesque sollicitudin ex et dictum faucibus.
            </p>
        </div>

        <!-- Pengurus Section -->
        <section class="mb-16">
            <h2 class="text-3xl md:text-4xl font-bold text-center text-gray-900 mb-12">
                Pengurus
            </h2>
            
            <!-- Carousel Container -->
            <div class="relative max-w-5xl mx-auto">
                <!-- Previous Button -->
                <button 
                    onclick="scrollCarousel(-1)" 
                    class="absolute left-0 top-1/2 -translate-y-1/2 -translate-x-4 z-20 bg-white rounded-full p-3 shadow-lg hover:bg-gray-100 transition-colors"
                >
                    <svg class="w-6 h-6 text-gray-800" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
                    </svg>
                </button>

                <!-- Carousel Wrapper -->
                <div class="overflow-hidden py-8">
                    <div id="pengurus-carousel" class="carousel-container flex items-end justify-center gap-6">
                        <!-- Cards will be generated by JavaScript -->
                    </div>
                </div>

                <!-- Next Button -->
                <button 
                    onclick="scrollCarousel(1)" 
                    class="absolute right-0 top-1/2 -translate-y-1/2 translate-x-4 z-20 bg-white rounded-full p-3 shadow-lg hover:bg-gray-100 transition-colors"
                >
                    <svg class="w-6 h-6 text-gray-800" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
                    </svg>
                </button>
            </div>
        </section>

        <!-- Staff Section -->
        <section class="mb-16">
            <h2 class="text-3xl md:text-4xl font-bold text-center text-gray-900 mb-12">
                Staff
            </h2>
            
            <!-- Staff Grid -->
            <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
                <!-- Staff Card 1 -->
                <div class="group bg-white rounded-2xl overflow-hidden shadow-md hover:shadow-2xl transition-all duration-300 hover:scale-105 cursor-pointer">
                    <img 
                        src="https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&h=400&fit=crop" 
                        alt="Staff 1" 
                        class="w-full h-80 object-cover"
                    >
                    <div class="p-4 text-center">
                        <h3 class="text-lg font-bold text-gray-900">
                            Budi Santoso
                        </h3>
                    </div>
                </div>
                
                <!-- Staff Card 2 -->
                <div class="group bg-white rounded-2xl overflow-hidden shadow-md hover:shadow-2xl transition-all duration-300 hover:scale-105 cursor-pointer">
                    <img 
                        src="https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=400&fit=crop" 
                        alt="Staff 2" 
                        class="w-full h-80 object-cover"
                    >
                    <div class="p-4 text-center">
                        <h3 class="text-lg font-bold text-gray-900">
                            Siti Nurhaliza
                        </h3>
                    </div>
                </div>
                
                <!-- Staff Card 3 -->
                <div class="group bg-white rounded-2xl overflow-hidden shadow-md hover:shadow-2xl transition-all duration-300 hover:scale-105 cursor-pointer">
                    <img 
                        src="https://images.unsplash.com/photo-1556157382-97eda2d62296?w=400&h=400&fit=crop" 
                        alt="Staff 3" 
                        class="w-full h-80 object-cover"
                    >
                    <div class="p-4 text-center">
                        <h3 class="text-lg font-bold text-gray-900">
                            Dewi Lestariiii
                        </h3>
                    </div>
                </div>
                
                <!-- Staff Card 4 -->
                <div class="group bg-white rounded-2xl overflow-hidden shadow-md hover:shadow-2xl transition-all duration-300 hover:scale-105 cursor-pointer">
                    <img 
                        src="https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop" 
                        alt="Staff 4" 
                        class="w-full h-80 object-cover"
                    >
                    <div class="p-4 text-center">
                        <h3 class="text-lg font-bold text-gray-900">
                            Rina Wijaya
                        </h3>
                    </div>
                </div>
            </div>
        </section>
    </main>
</body>
</html>